Vagrant.configure("2") do |config|
  (1..5).each do |i|
    config.vm.define "maquina_#{i}" do |maquina|
      maquina.vm.box = "centos/7"
      maquina.vm.network "public_network", bridge: "wlan0", ip: "192.168.1.12#{i}"      
      maquina.vm.provision "shell", inline: <<-SHELL
        sudo hostnamectl set-hostname "node#{i}"
        alias cls="clear"
      SHELL
      maquina.vm.provision "shell", path: "install_docker.sh"
    end
  end
end