Vagrant.configure("2") do |config|
  (1..2).each do |i|
    config.vm.define "web_#{i}" do |web|
      web.vm.box = "centos/7"
      web.vm.network "public_network", bridge: "Realtek Gaming GbE Family Controller", ip: "192.168.1.12#{i}"
      web.vm.provision "shell", path: "httpsd_#{i}.sh"
    end
  end

  (1..2).each do |i|
    config.vm.define "lb_ipvsadm#{i}" do |lb_ipvsadm|
      lb_ipvsadm.vm.box = "centos/7"
      lb_ipvsadm.vm.network "public_network", bridge: "Realtek Gaming GbE Family Controller", ip: "192.168.1.12#{i+2}"
      lb_ipvsadm.vm.provision "shell", path: "lb_ipvsadm.sh"
    end
  end
end