Vagrant.configure("2") do |config|

  nodes = [
    { name: "master", ip: "192.168.1.121"},
    { name: "worker", ip: "192.168.1.122"}
    # { name: "worker", ip: "192.168.1.123"},
    # { name: "worker", ip: "192.168.1.124"},
    # { name: "worker", ip: "192.168.1.125"},
  ]

  nodes.each do |node|
    config.vm.define node[:name] do |n|
      n.vm.box = "centos/7"
      n.vm.network "public_network", bridge: "Realtek Gaming GbE Family Controller", ip: node[:ip] 
      n.vm.provision "shell", path: "install_docker.sh"
      n.vm.hostname = node[:name]
    end
  end
end